export const CONSTANTS = {
  MIN_WEIGHT: 0,
  MAX_WEIGHT: 200,
  FPS: 30,
  THRESHOLD_WEIGHT_DIFFERENCE: 5,
  WEBSOCKET_RETRY_CONNECTION: 5,
  WEBSOCKET_RETRY_PAUSE_MS: 5000,
  ADHOC_WORKOUT_ID: -1,
};
