/**
 ** This file is generated by scripts/envToConsts.py
 **/
export const ENV_VARIABLES = {
  USE_SERVER: true,
  SERVER_IP: "127.0.0.1",
  SERVER_PORT: 8654,
  SERVER_WEBSOCKET_PORT: 8655,
  WEBCLIENT_IP: "127.0.0.1",
  WEBCLIENT_PORT: 8653,
}